### PR TITLE
Update convert_annotations.py

### PR DESCRIPTION
**Pull request by cyberjam**
I edit line 40, line 63 for exception, compound.

### CODE REVIEW

**Comment by rbell1988** [comment]
This is for the person who wrote "convert_annotations.py". You should first learn python, go study. Especially about the purpose of "with" statement, disk IO and string.join function.

**Comment by cyberjam** [comment]
> This is for the person who wrote "convert_annotations.py". You should first learn python, go study. Especially about the purpose of "with" statement, disk IO and string.join function.

You said it because you can do it well, right? I'm sure you came here with the same problem. I'm not good at Python, so can you program it for us?😇

**Comment by rbell1988** [comment]
I’ve already wasted time figuring out what’s wrong with the code you wrote.

**Comment by orphan2020** [comment]
when running python convert_annotations.py I get the error:

Traceback (most recent call last):
  File "convert_annotations.py", line 64, in <module>
    coords = convert(filename_str, coords)
  File "convert_annotations.py", line 18, in convert
    coords[0] /= int(image.shape[1])
AttributeError: 'NoneType' object has no attribute 'shape'

**Pull request closed without merging**
